# Generated by Django 5.2.5 on 2025-08-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_rename_emergency_contact_patientprofile_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
