# Generated by Django 5.2.5 on 2025-08-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patientprofile_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='birthdate',
            field=models.DateField(blank=True),
        ),
    ]
