# Generated by Django 5.2.4 on 2025-07-12 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctorprofile_address_doctorprofile_contact_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='address',
            new_name='clinic_address',
        ),
    ]
